# Generated by Django 5.2.8 on 2025-11-29 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(help_text='Our internal transaction reference', max_length=100, unique=True)),
                ('chapa_reference', models.CharField(blank=True, help_text="Chapa's transaction reference (tx_ref)", max_length=100, null=True)),
                ('checkout_url', models.URLField(blank=True, help_text='Chapa checkout URL for customer payment', max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in ETB', max_digits=10)),
                ('currency', models.CharField(default='ETB', help_text='Currency code (ETB for Ethiopian Birr)', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (e.g., telebirr, cbebirr)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'), models.Index(fields=['payment_status'], name='payments_pa_payment_8ac9aa_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
