# Generated by Django 5.2.8 on 2025-11-29 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code (e.g., SUMMER2024)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], help_text='Type of discount: percentage or fixed amount', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (e.g., 20 for 20% or 100 for 100 ETB)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase amount required to use this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null = unlimited)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('valid_from', models.DateTimeField(help_text='Date and time when coupon becomes valid')),
                ('valid_to', models.DateTimeField(help_text='Date and time when coupon expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='coupons_cou_code_1aa9c7_idx')],
            },
        ),
    ]
